### ISSUE TITLE
No such image

### ISSUE THREAD

**Issue by volderette** [abhioncbr/docker-superset#18]
I'm getting a "ERROR: no such image: abhioncbr/docker-superset" on docker-compose up -d.
Is this a temporal error? I thought I've tried it before with more luck...

**Comment by abhioncbr** [comment]
@volderette firstly, thanks for using the image and putting the bug. 

Are you following the setup as I mentioned in the [blog](https://medium.com/@abhioncbr/docker-image-of-apache-superset-400cf4855b9). It seems like from the error you are getting that `.env` file is not getting read. The [directory structure](https://gist.githubusercontent.com/abhioncbr/decf9d89fa5cade5c7464796b592493d/raw/a9649bf793fd33a97ce691b0f913c681ae4b5019/directory-strcture.md) should be like that.

**Comment by volderette** [comment]
Thanks, downloading the file first and moving it in the directory fixed the problem.
If I directly download to the right docker folder, something strange happens and it doesn't work. So I guess it's some rights problem on my side.
