### ISSUE TITLE
ENV not set?

### ISSUE THREAD

**Issue by volderette** [abhioncbr/docker-superset#19]
I'm using your .env variable, but I get:

WARNING: The MYSQL_USER variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_DATABASE variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The SUPERSET_VERSION variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_HOST variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_PORT variable is not set. Defaulting to a blank string.
WARNING: The REDIS_HOST variable is not set. Defaulting to a blank string.
WARNING: The REDIS_PORT variable is not set. Defaulting to a blank string.
WARNING: The SUPERSET_ENV variable is not set. Defaulting to a blank string.
WARNING: The GOOGLE_APPLICATION_CREDENTIALS variable is not set. Defaulting to a blank string.

**Comment by abhioncbr** [comment]
All these variables are in the file https://github.com/abhioncbr/docker-superset/blob/master/docker-files/.env. If it is getting read then all will be set.

**Comment by volderette** [comment]
Thanks for your help, fixed with the other issue. Both on my side!

**Comment by abhioncbr** [comment]
@volderette glad to know that it's working for you now. If you like the project, please give a start to the repo.
