### ISSUE TITLE
Options to edit Username, Email address and add Email Reporting

### ISSUE THREAD

**Issue by chharish** [abhioncbr/docker-superset#23]
Thanks for the docker. Saved so much time and works without any issues! 
Especially there are several issues with the original superset container like [entering restarting loop with exit code 243](https://github.com/apache/incubator-superset/issues/6887), [missing CSS styling](https://github.com/apache/incubator-superset/issues/6694). This worked like a charm without editing any files. 

However, now I'm out of sync with the original superset documentation. Is there a way to edit username, email address of the user before/after the docker is deployed?

Also say for example, if I need features like email reporting, how to get it to work?

**Comment by abhioncbr** [comment]
Thanks, @chharish  for appreciation. I have built the image with the same intent of easy usability.
Regarding, the email and username it's all the same as per the documentation. Default user to login is `admin` and password is the same, i.e. `admin.` You can add multiple users after logging.

Also, I don't think Superset currently is supporting email reporting feature. If it's there, please share the documentation, I will look into it.

**Comment by chharish** [comment]
My bad. I reviewed the dashboard for list users. From under list users > I was able to edit email and username as well http://<ip>/users/edit/1. 
Just not sure why it is not editable from under profile http://<ip>/userinfoeditview/form  

Thanks for clarifying on email reporting.
