### ISSUE TITLE
local postgresql connection failure

### ISSUE THREAD

**Issue by dominijk** [abhioncbr/docker-superset#34]
**Describe the bug**
Deploying through kitematic I'm unable to connect to a postgres db running on local host. Pyscog seems to be successfully installed

```bash
Loaded your LOCAL configuration at [/home/superset/config/superset_config.py]
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Recognized Database Authentications.
Admin User admin created.
Loaded your LOCAL configuration at [/home/superset/config/superset_config.py]
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
```

**To Reproduce**
Add new database
Enter URI as 
`postgresql://username:@localhost:5432/dbname`

**Expected behavior**
Test connection should be successful instead receive error

````
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n(psycopg2.OperationalError) could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432?
````
Db is accessible through that address

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Desktop
 - OS: Mac
 - Browser Chrome 
 - Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

**Comment by abhioncbr** [comment]
@dominijk If I am understanding is correct, you are trying to connect Postgres database instance running on the host machine inside Superset docker container using Kitematic. You can't connect it using 'localhost', please try to follow as per this post - https://nickjanetakis.com/blog/docker-tip-35-connect-to-a-database-running-on-your-docker-host.

**Comment by dominijk** [comment]
@abhioncbr Thankyou so much for reference on the latest docker using the tip here - https://nickjanetakis.com/blog/docker-tip-65-get-your-docker-hosts-ip-address-from-in-a-container 

Let me know what you need to do is;

`postgresql+psycopg2://username:password@host.docker.internal:port_number/database`
