### ISSUE TITLE
Accessing The Volumes

### ISSUE THREAD

**Issue by Mellorison** [abhioncbr/docker-superset#37]
Hi.
I would like to know how to access the superset asset files.

**Comment by abhioncbr** [comment]
You can access the volumes by using the `docker exec` command. You can explore the whole file-system of the container using `exec`.

**Comment by Mellorison** [comment]
Will this give me access to the superset asset files?

**Comment by abhioncbr** [comment]
try, `sudo docker exec -it a1e5ee21eaa1ba238e3b7154c129d0767e6576993addd9cd94899f38d8abb2f7 /bin/bash` and once you are inside the container, list all the files and view the content what you want to see.

**Comment by Mellorison** [comment]
Alright. It's worked. Thanks a lot!
