### ISSUE TITLE
elasticsearch connection error

### ISSUE THREAD

**Issue by azarzar15** [abhioncbr/docker-superset#40]
**Describe the bug**
error:
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:elasticsearch.https"}

when adding elasticsearch data source

**To Reproduce**
1. Go to 'Sources'
2. Click on 'Databases'
3. Click on Add Database
4. Add Elasticsearch HTTPS with Authentication
5. Click on Test Connection

**Expected behavior**
success with the test connection

Latest Superset install using the docker-compose

**Comment by abhioncbr** [comment]
Elastic search api installed in latest(0.36.0 & 0.35.1) version. New images are uploaded on docker-hub. Can you please try again?

**Comment by abhioncbr** [comment]
PR request, https://github.com/abhioncbr/docker-superset/pull/44/files
