### ISSUE TITLE
Update docker image to Superset 0.36

### ISSUE THREAD

**Issue by yanickrochon** [abhioncbr/docker-superset#41]
**Is your feature request related to a problem? Please describe.**

Superset 0.36 uses SMART_NUMBER when displaying graphs, but the current image does not support this data type.

**Describe the solution you'd like**

Update image to the latest Superset tag

**Describe alternatives you've considered**

Other than not use this solution? We haven't considered anything at this point.

**Additional context**

We just started using Superset, and we moved from the incubator after learning that it was not suitable outside of development.

**Comment by abhioncbr** [comment]
Latest Image 0.36.0 uploaded to docker-hub, can you guys try. Also, elastic-search plugin dependency installed too.

**Comment by abhioncbr** [comment]
PR request, #44
