### ISSUE TITLE
Docker won't rebuild

### ISSUE THREAD

**Issue by yanickrochon** [abhioncbr/docker-superset#42]
**Describe the bug**

```
# docker-compose build
redis uses an image, skipping
mysql uses an image, skipping
superset uses an image, skipping

# docker-compose images
ERROR: no such image: sha256:13b0147efffc26b489f6aafda0370c3ef3afd936548a6cbe75ef9d84158fb7f1: No such image: sha256:13b0147efffc26b489f6aafda0370c3ef3afd936548a6cbe75ef9d84158fb7f1
```

I manually removed the image because the `docker-compose build` would not rebuild. Now the image is gone and it still won't build.

**To Reproduce**
1. `docker-compose build` won't do anything
2. `docker rmi 5874cfce8261` will remove `abhioncbr/docker-superset`
3. `docker-compose build` still won't do anything

**Expected behavior**
Rebuilding the container if it is no longer present for whatever reason.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Browser n/a
 - Version latest

**Additional context**
Superset is not at the latest version. See issue #41.

**Comment by abhioncbr** [comment]
I will look into the issues, yes it's a while that I didn't promote the changes for the recent Superset released version. Thanks.

**Comment by abhioncbr** [comment]
Yes, Superset changed the packaging in the code in latest version. The new image(0.36.0) is there on docker-hub. Can you please try?

**Comment by abhioncbr** [comment]
PR request, #44
